### ISSUE TITLE
Use an ORM for robustness

### ISSUE THREAD

**Issue by Alexandregirbal** [Alexandregirbal/Rankify#3]
Pour commencer j'ai pris le client mongo en mode bourrin, il faudrait utiliser un ORM pour un minimum de validation.
J'ai décider de partir sur **Drizzle** car askip c'est bien.

**Comment by gdamou** [comment]
https://github.com/drizzle-team/drizzle-orm/issues/2377

**Comment by Alexandregirbal** [comment]
Peut être que ce package peut le faire: [zod-mongoose](https://www.npmjs.com/package/@zodyac/zod-mongoose)
